FROM centos
MAINTAINER fliay
#把宿主机当前上下文的a.txt 拷贝到容器/usr/local/路径下
COPY a.txt /usr/local/cincontainer.txt
#把java与tomcat添加到容器中
ADD apache-tomcat-9.0.27.tar.gz /usr/local/
ADD jdk-8u231-linux-x64.tar.gz  /usr/local/
#安装vim编辑器
RUN yum -y install vim
#设置工作访问时候的WORKDIR路径，登录的落脚点
ENV MYPATH /usr/local
WORKDIR $MYPATH
#配置java与tomcat环境变量
ENV JAVA_HOME /usr/local/jdk1.8.0_231
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV CATALINA_HOME /usr/local/apache-tomcat-9.0.27
ENV CATALINA_BASE /usr/local/apache-tomcat-9.0.27
ENV PATH $PATH:$JAVA_HOME/bin:CATALINA_HOME/lib:CATALINA_HOME/bin
#容器运行时监听的端口
EXPOSE 8080
#启动时运行tomcat
#ENTRYPOINT["/usr/local/apache-tomcat-9.0.27/bin/startup.sh"]
#CMD["/usr/local/apache-tomcat-9.0.27/bin/catalina.sh","run"]
CMD /usr/local/apache-tomcat-9.0.27/bin/startup.sh && tail -F /usr/local/apache-tomcat-9.0.27/bin/log/catalina.out

docker run -d -p 8081:8080 --name mytomcat9_01 -v  /home/fliay/tomcat9/test:/usr/local/apache-tomcat-9.0.27/webapps/test -v /home/fliay/tomcat9/tomcat9logs/:/usr/local/apache-tomcat-9.0.27/logs --privileged=true mytomcat9



  docker build -t mytomcat9 .




 MYSQL
 
 docker run --name mysql  --restart=always  -p 3306:3306  -v /home/fliay/mysql/conf.d:/etc/mysql/conf.d   -v /home/fliay/mysql/logs:/logs  -v /home/fliay/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.6
 
 
 
 
 
 
 
 docker run -ti -d --restart=always --name shipyard-rethinkdb rethinkdb
 
 
docker run -ti -d -p 4001:4001 -p 7001:7001 --restart=always --name shipyard-discovery microbox/etcd:latest -name discovery
 
docker run -ti -d -p 2375:2375 --hostname=$HOSTNAME --restart=always  --name  shipyard-proxy  -v /var/run/docker.sock:/var/run/docker.sock  -e  PORT=2375 shipyard/docker-proxy:latest
 
docker run -ti -d --restart=always --name shipyard-swarm-manager swarm:latest  manage  --host  tcp://0.0.0.0:3375  etcd://192.168.50.200:4001
 
docker run -ti -d --restart=always --name shipyard-swarm-agent swarm:latest join --addr 192.168.137.100:2375 etcd://192.168.50.200:4001
 
docker run -ti -d --restart=always --name shipyard-controller --link shipyard-rethinkdb:rethinkdb --link shipyard-swarm-manager:swarm -p 8080:8080 shipyard/shipyard:latest server -d tcp://swarm:3375
 
 
 





